name: Terraform plan
on:
  workflow_dispatch:

permissions: write-all

jobs:
  terraform-plan:
    runs-on: self-hosted
    steps:
    - name: Azure Login
      uses: Azure/login@v3
      with:
        client-id: d92cf514-63bf-420a-9d83-33b05cffe961
        tenant-id: 0ea3b997-cc5d-4c90-a4a4-5c41a2364f32
        subscription-id: f3dd8656-66bf-4af3-bce9-c04adf655c30
    - name: Terraform init
      run: terraform init
      working-directory: environments/sandbox
    - name: Terraform fmt
      run: terraform fmt
      working-directory: environments/sandbox
    - name: Terraform validate
      run: terraform validate
      working-directory: environments/sandbox
    - name: Terraform plan
      run: terraform plan
      working-directory: environments/sandbox

    
      
  
  
